[package]
name = "pista-feeds"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
binance = "0.18.4"
chrono = "0.4.22"
clap = {version = "3.0", features = ["derive"]}
env_logger = "0.9.0"
libc = "0.2.134"
log = "0.4.17"
mpd = "0.0.12"
notify = "5.0.0"
reqwest = {version = "0.11.11", features = ["blocking"]}
serde = { version = "1.0.144", features = ["derive"] }
serde-xml-rs = "0.6.0"
serde_json = "1.0.82"
x11 = { version = "2.20.0", features = ["xlib"] }

[[bin]]
name = "pista-feed-backlight-laptop"
path = "pista-feed-backlight-laptop.rs"

[[bin]]
name = "pista-feed-bluetooth"
path = "pista-feed-bluetooth.rs"

[[bin]]
name = "pista-feed-disk"
path = "pista-feed-disk.rs"

[[bin]]
name = "pista-feed-helium-account-balance"
path = "pista-feed-helium-account-balance.rs"

[[bin]]
name = "pista-feed-memory"
path = "pista-feed-memory.rs"

[[bin]]
name = "pista-feed-mpd"
path = "pista-feed-mpd.rs"

[[bin]]
name = "pista-feed-volume"
path = "pista-feed-volume.rs"

[[bin]]
name = "pista-feed-weather"
path = "pista-feed-weather.rs"

[[bin]]
name = "pista-feed-x11-keymap"
path = "pista-feed-x11-keymap.rs"
